### PR TITLE
finished api endpoints frontend

### PR DESCRIPTION
**Pull request by vincentpalomo**
do not merge until fixed

### CODE REVIEW

**Comment by vincentpalomo** [comment]
should be good to go now

**Comment by vincentpalomo** [comment]
finished all api endpoints

**Comment by vincentpalomo** [comment]
close this pull need a new pull request for frontend components

**Comment by vincentpalomo** [comment]
can close out this pull request, need to start a new branch for frontend component rendering

**Review by AMT98 — APPROVED** [review]
Good work partner.

**Pull request merged**
